module.exports = {
  ...require("./depart.controller.js"),
  ...require("./designation.controller.js"),
  ...require("./empl.controller.js"),
  ...require("./user.controller.js"),
  ...require("./stock.controller.js"),
  ...require("./income.controller.js"),
  ...require("./spareParts.controller.js"),
  ...require("./customer.controller.js"),
  ...require("./hr.controller.js"),
  ...require("./attendance.controller.js"),
  ...require("./erp.controller.js"),
  ...require("./supplier.controller.js"),
  ...require("./reports.controller.js"),
  ...require("./dashboard.controller.js"),
  ...require("./role.controller.js"),
  ...require("./purchase.controller.js"),
  ...require("./rawMaterial.controller.js"),
  ...require("./payroll.controller.js"),
  quotation: require("./quotation.controller.js"),
  salesOrder: require("./salesOrder.controller.js"),
  invoice: require("./invoice.controller.js"),
  payment: require("./payment.controller.js"),
  salesReturn: require("./salesReturn.controller.js"),
  salesDashboard: require("./salesDashboard.controller.js"),
};