const mongoose = require('mongoose');

const erpRecordSchema = new mongoose.Schema({
  id: { type: String, required: true },
  module: {
    type: String,
    required: true,
    enum: ['payroll', 'purchase', 'sales', 'warehouse', 'service', 'accounts'],
  },
  recordType: { type: String, required: true },
  emp: String,
  empId: String,
  employeeId: { type: mongoose.Types.ObjectId, ref: 'employee' },
  name: String,
  contact: String,
  phone: String,
  city: String,
  gst: String,
  supplier: String,
  customer: String,
  party: String,
  month: String,
  basic: Number,
  allowances: Number,
  deductions: Number,
  net: Number,
  type: String,
  amount: Number,
  date: String,
  items: Number,
  delivery: String,
  due: String,
  dueDate: String,
  validTill: String,
  reason: String,
  qty: Number,
  part: String,
  from: String,
  to: String,
  po: String,
  receivedBy: String,
  generated: String,
  engineer: String,
  machine: String,
  issue: String,
  priority: String,
  ticket: String,
  parts: String,
  hours: String,
  cost: String,
  assigned: Number,
  inProgress: Number,
  resolved: Number,
  expertise: String,
  available: String,
  debit: Number,
  credit: Number,
  balance: Number,
  gstAmount: Number,
  period: String,
  revenue: Number,
  expenses: Number,
  profit: Number,
  location: String,
  capacity: String,
  manager: String,
  status: { type: String, default: 'Active' },
  entityType: { type: String },
  notes: String,
}, { timestamps: true });

erpRecordSchema.index({ module: 1, recordType: 1 });

module.exports = mongoose.model('erprecord', erpRecordSchema);
