module.exports = {
  ...require("./User.model.js"),
  ...require("./Empl.model.js"),
  ...require("./Designation.model.js"),
  ...require("./Depart.model.js"),
  ...require("./Payroll.model.js"),
  ...require("./Customer.model.js"),
  ...require("./SpareParts.model.js"),
  ...require("./Category.model.js"),
  ...require("./Quotation.model.js"),
  ...require("./SalesOrder.model.js"),
  ...require("./Invoice.model.js"),
  ...require("./Payment.model.js"),
  ...require("./SalesReturn.model.js"),
  ...require("./Warranty.model.js"),
  ...require("./ServiceRequest.model.js"),
};